# Generated by Django 4.1.7 on 2023-03-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oncologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_research', models.CharField(max_length=150)),
                ('image', models.CharField(default='Beautiful image', max_length=150)),
                ('medical_examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.medicalexamination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='oncologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.oncologist'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.patient'),
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_research', models.CharField(max_length=150)),
                ('result', models.TextField(max_length=400)),
                ('medical_examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.medicalexamination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_research', models.CharField(max_length=150)),
                ('report', models.TextField(max_length=400)),
                ('medical_examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.medicalexamination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oncologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.oncologist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.patient')),
            ],
        ),
    ]
